---

- hosts: dp-yarn-slave
  roles: 
    - samza_monitor_utilities
  become: yes
 
- hosts: dp-yarn-master
  roles:
    - samza_monitor_utilities
  become: yes


- hosts: influxdb
  roles: 
    - samza_monitor_utilities
  become: yes
