- hosts: spark
  become: yes
  become_user: "{{user}}"
  roles:
    - data-products-fetch-logs
  serial: 1

- hosts: analytics-api
  become: yes
  become_user: "{{user}}"
  roles:
    - analytics-api-fetch-logs
  serial: 1

- hosts: dp-cassandra
  roles:
    - cassandra-fetch-logs
  serial: 1

- hosts: secor
  roles:
    - secor-fetch-logs
  serial: 1
