---
- hosts: dp-yarn-slave
  vars_files:
    - "{{ secrets_path }}"	 	 
  tasks:
   - command: "./upload_samza_logs.sh {{CONTAINER_NAME_SAMZA}} {{ACCOUNT_NAME_SAMZA}} {{azure_account_key}}"
     args:
       chdir: "{{script_path}}"
     become: yes
