---
- name: Create /opt/kibana_oauth_proxy/bin directory
  file: path=/opt/kibana_oauth_proxy/bin state=directory mode=755 recurse=yes

- name: Create kibana_oauth_proxy log directory
  file: path=/var/log/kibana_oauth_proxy state=directory mode=755

- name: Create /etc/kibana_oauth_proxy directory
  file: path=/etc/kibana_oauth_proxy state=directory mode=755 recurse=yes

- name: copy oauth proxy binary
  copy: src=oauth2_proxy dest=/opt/kibana_oauth_proxy/bin mode=755

- name: Copy authenticated_emails.txt
  template: src=authenticated_emails.txt dest=/etc/kibana_oauth_proxy mode=0644

- name: Copy Config file
  template: src=config.cfg dest=/opt/kibana_oauth_proxy mode=0644

- name: Copy kibana_oauth_proxy init.d script
  template: src=kibana_oauth_proxy.sh dest=/etc/init.d/kibana_oauth_proxy mode=755

- name: Start kibana_oauth_proxy
  service: name=kibana_oauth_proxy state=restarted enabled=yes
