---
- name: Install logrotate
  apt: name=logrotate state=present
  sudo: yes

- name: Install pip
  apt: name=python-pip state=present
  sudo: yes

- name: Install aws-cli
  command:  pip install awscli
  sudo: yes

- name: copy EP artifact
  copy: src="{{ep_artifact}}" dest="{{ecosystem_folder_temp}}" owner=ecosystem group=ecosystem

- name: create EP folder
  file: path="{{ ecosystem_folder }}" state=directory owner=ecosystem group=ecosystem

- name: extract artifact
  unarchive: src="{{ecosystem_folder_temp}}/{{ep_artifact}}" dest="{{ ecosystem_folder }}" copy=no
  sudo: yes

- name: Install bundler
  gem: name=bundler state=latest

- name: Install libmysqlclient-dev
  apt: name=libmysqlclient-dev state=present

- name: Install mysql2 gem
  gem: name="mysql2"

- name: Bundle install gems
  command: bash -lc " rm Gemfile.lock && bundle --path vendor/bundle"
  args:
    chdir: "{{ ecosystem_folder }}/tasks"

- name: Create log directory for cron job
  file:
    path="{{ ep_log_dir }}"
    state=directory
    mode=755
    owner="{{ ecosystem_user }}"
    group="{{ ecosystem_user }}"
  sudo: yes    
