---
- name: Create folder for logrotate config
  file:
    path={{item}}
    state=directory
    mode=755
    owner=root
    group=root
  sudo: yes
  with_items:
    - /etc/partners
    - /etc/public_data

- name: Copy logrotate config file for partner
  template: src=partner.logrotate dest=/etc/partners/partner.logrotate mode=0644
  sudo: yes

- name: Copy logrotate config file for public
  template: src=public.logrotate dest=/etc/public_data/public.logrotate mode=0644
  sudo: yes

- name: Create folder for logs
  file:
    path=/var/log/{{item}}
    state=directory
    mode=775
    owner=logstash
    group=logstash
    recurse=yes
  sudo: yes
  with_items:
   - partners
   - public_data

- name: Add ecosystem to logstash group
  user: name=ecosystem group=logstash
  sudo: yes

- name: Cron job for public data logrotate
  cron: name="public data logrotate"
    user=root minute="10" job="/usr/sbin/logrotate -f /etc/public_data/public.logrotate > /dev/null"

- name: Cron job for partner logrotate
  cron: name="partner logrotate"
    user=root minute="10" job="/usr/sbin/logrotate -f /etc/partners/partner.logrotate > /dev/null"


- name: Create folder for archiving
  file:
    path="/var/log/{{item}}"
    state=directory
    mode=755
    owner=ecosystem
    group=ecosystem
  with_items:
   - partners-archive
   - public_data_archive


- name: Cron job for partner-data-archiver
  cron: name="partner data archiver"
    user=root minute="10" job="/bin/bash -l -c 'cd {{ ecosystem_folder }}/tasks/ && EP_LOG_DIR={{ ep_log_dir }} bundle exec rake scheduled:archive_file --silent > /dev/null'"

- name: Cron job for public-data-archiver
  cron: name="public data archiver"
    user=root minute="15" job="/bin/bash -l -c 'cd {{ ecosystem_folder }}/tasks/ && EP_LOG_DIR={{ ep_log_dir }} PROGNAME=public_data_archiver.jobs.ep bundle exec rake scheduled:archive_public_data --silent > /dev/null'"