- name: Copy data_aggregate config
  template: src={{item}}.yml dest={{ ecosystem_folder }}/lib/ecosystem-platform/config/{{item}}.yml owner={{ ecosystem_user }} group={{ ecosystem_user }}
  with_items:
   - public
   - private

- name: Cron job for public-data-aggregator
  cron: name="public data aggregator"
    user=ecosystem hour="2" minute="0" job="/bin/bash -l -c 'cd {{ ecosystem_folder }}/tasks/ && EP_LOG_DIR={{ ep_log_dir }} bundle exec rake scheduled:public_data_aggregator --silent > /dev/null'"

- name: Cron job private-data-aggregator for partner
  cron: name="private data aggregator"
    user=ecosystem hour="2" minute="15" job="/bin/bash -l -c 'cd {{ ecosystem_folder }}/tasks/ && EP_LOG_DIR={{ ep_log_dir }} bundle exec rake scheduled:partner_data_aggregator --silent > /dev/null'"

