analytics_api:
   root: "{{ analytics.home }}/api"
   home: "{{ analytics.home }}/api/analytics-api-1.0"
   service_args: -Dconfig.file=/mount/data/analytics/api/{{ env }}.conf
   paths: ['/home/analytics/sbin', '/mount/data/analytics', '/mount/data/analytics/logs', '/mount/data/analytics/logs/services', '/mount/data/analytics/logs/api-service', '/mount/data/analytics/api', '/mount/data/analytics/tmp', '/mount/data/analytics/scripts/monitor-data']
cassandra:
  keyspace_prefix: "{{ env }}_"
