- name: Installing prerequisites
  become: yes
  apt: 
    name: apt-transport-https
    state: installed

- name: Add Azure apt repository
  become: yes
  apt_repository: 
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ xenial main'
    state: present

- name: Import Azure signing key
  become: yes
  apt_key:
    url:  https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: ensure azure-cli and apt-transport-https is installed
  become: yes
  apt:
    name: azure-cli
    state: installed
    update_cache: yes
